### ISSUE TITLE
Too many channels on Discord

### ISSUE THREAD

**Issue by bitcoinx2** [wispproject/doc#1]
I would suggest reducing the channels to the essentials, to reduce confusion and make things simpler and more transparent. I would suggest the following channels:

1. welcome (for Discord welcome messages)
2. announcements
3. general
4. contributors (only people with the "contributor" role can post, readable for everyone)
5. support
6. marketing
7. development
8. off-topic

Instead of a proposals channel, we should use Github issues here, as there are many advantages to that, compared to a Discord channel:
* It is searchable (there is a search function for Issues)
* It doesn't get lost when more things are getting posted
* People can comment right under it, to keep everything in one location
* It can be closed after the problem has been solved.
* Each issue has a unique link that can be referred to.

**Comment by Jreinhardt996** [comment]
reorganized channels, thanks for the suggestion!
